### ISSUE TITLE
[Feature Reqest] Add Union mounting of multiple archives to the same directory.

### ISSUE THREAD

**Issue by detain** [andrew-grechkin/fuse3-p7zip#10] opened 2023-11-05 03:20 UTC
I have a bunch of 7z files in a /source/dir and each one is being mounted into the same /destination/dir.  Instead of a different process for each archive could we allow passing multiple archives to be mounted in a single directory?

**Comment by andrew-grechkin** [comment] 2023-11-05 09:21
There is no need for such functionality in fuse3-p7zip itself. This is against unix philosophy.
It can be done with a simple script:

```bash
#!/usr/bin/env bash

set -Eeuo pipefail

if [[ "$#" -lt 2 ]]; then
    echo "pass at least 2 arguments: <mount_point_root> <archive> [<archive>]"
    exit 1
fi

TARGET="${1}"
shift

for ARCHIVE in "$@"; do
    MOUNT_POINT="$TARGET/$(basename "$ARCHIVE")"
    mkdir -p "$MOUNT_POINT"
    echo "mounting to '$MOUNT_POINT': '$ARCHIVE'"
    fuse3-p7zip "$ARCHIVE" "$MOUNT_POINT"
done

```

Duplicate of #3

**Closed by andrew-grechkin** 2023-11-05 09:21 UTC
